travis:
  secure:
    BINSTAR_TOKEN: mRU2zX1WAat9b6n+pXjleE7gLG8cIK5DuThj5rxSsyMuB2WLF5hPPTXiSbf1PK6XreoDuoi9H7quKMxXNQgK1y3YByp7TLpkaRfg+OpgDfyWOI02Bm3P7w8k8ZiMAjnPGeLHLypa3iQEjdAc6SBS3al/K352fYZIG1D1kyajUJka6atDQHc9MX1jBfa0R5KNa7e2vsUGG735dqTl5hpssbzEIGRYLF2QVdXOACcU+ClIXrhmzi+37JAhvY9ZzJgOlchuIW6cuFDCZvU90oWvDgPEmn01wrWDHgXs71jLcZ46J7LBgXJre9oYXC0ev0lQdir21+RhGRIvLyHcmHNNlgh/kK8KSo3zQ6uWL3rPPW+SY0xe5t4nr/rpXJEeJYUOwJ/LO6lCdlfJETTfATOQfJMsoG5nCC/EAp/xts0yzOp04/GaGmNfg5NfG8/t73hHIyssn9CsvhewzRDAUWFAWufwbBCGYMzOosoqdCP/DS9WFR+zhFeHkHbN6TjW8BAR44mp71RqPpbboIlLBsilhrr+884Lws0likp3Ir1qK1+LK6J1T9FHRxzZ1zVgra9rsSCM/ljCfp0bJCtzZ+ptYtgkB1AiuKqae+S3xHhFKrdDn3T3TaGHPkz0vQVTzyv4pR2l1b81s+8Rx9tvkRlCWr3kz7r7owviV1SF7ILvVfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
